#!/bin/bash

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 PHASE 1 OPTIMIZATION TEST SCRIPT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This script will help you verify Phase 1 optimization results"
echo ""

# Check if app is running
if ! lsof -ti:8001 >/dev/null 2>&1; then
    echo "❌ Backend not running. Start it first!"
    echo "   cd backend && python start_uvicorn_gpu.py"
    exit 1
fi

echo "✅ Backend is running"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 MONITORING OPTIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Choose what to monitor:"
echo ""
echo "1. Real-time FPS"
echo "   tail -f backend/backend.log | grep -E 'FPS|fps'"
echo ""
echo "2. GPU Utilization"
echo "   watch -n 1 nvidia-smi"
echo ""
echo "3. Spatial-Temporal Matching (should still work)"
echo "   tail -f backend/backend.log | grep -E '🎯|✅ Matched'"
echo ""
echo "4. Unknown Person Detection"
echo "   tail -f backend/backend.log | grep -E 'Alert: Unknown|tracking started'"
echo ""
echo "5. All-in-One Dashboard"
echo "   watch -n 2 'echo \"=== FPS ===\"
echo "                grep FPS backend/backend.log | tail -5
echo "                echo ""
echo "                echo \"=== GPU ===\"
echo "                nvidia-smi --query-gpu=utilization.gpu,utilization.memory,temperature.gpu --format=csv,noheader
echo "                echo ""
echo "                echo \"=== Unknowns ===\"
echo "                grep \"tracking started\" backend/backend.log | wc -l
echo "                echo ""
echo "                echo \"=== Spatial Matches ===\"
echo "                grep \"🎯\" backend/backend.log | wc -l"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📈 COMPARISON METRICS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After running for 30-60 seconds, compare:"
echo ""
echo "Metric                    | Before      | After (Expected)"
echo "─────────────────────────────────────────────────────────"
echo "Average FPS               | 50-60       | 100-120"
echo "GPU Utilization           | 12-20%      | 12-20% (same)"
echo "Frame Processing Time     | ~17ms       | ~8-10ms"
echo "Unknown Detections        | Similar     | Similar"
echo "Spatial-Temporal Matches  | Active      | Active (wider window)"
echo "Duplicate Snapshots       | Low         | Low or better"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ SUCCESS CRITERIA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ FPS >= 90 (at least 1.5x improvement)"
echo "✓ Unknown persons still detected"
echo "✓ Spatial-temporal boost events visible in logs"
echo "✓ No increase in duplicate snapshots"
echo "✓ GPU utilization similar to before"
echo ""
